language: node_js
node_js:
 - '10'
script:
 - yarn test
 - yarn build
install:
 - yarn install --ignore-engines --pure-lockfile
deploy:
  provider: firebase
  token:
    secure: WM87LJOKhUMCxVKMksydeCDk6pfH/14AaHS3vpUoGfYHHgNGV7Q52AgumgZvCuopH53HBFL3Z+RNdMO1JhEZw7t2Z73CrgqLYhWhsgzqRfoYbri0FAfQLpUPe4GFN0Rr+dJT8EMgh+uSYcZlFVAl54p9sMu6BHlDAcUIZ6yysLqnMzUT76HmjvCzkbVBoOlYnErNFTq0Blvq8WfnTitZoLwv0HtNnvG90YGmZ4xGIKkoKzeB+JtCHxVg311FoTftonnNEDsdbv/m/r7TRH5ydcbL87DvPCaFqm1YflJiaRp9MvzMo9cg+hTK0byJyUfFWEFSY0G2pYnpovx4vGD1paeoJe7Rjx86OELFKyDpK1HDVT4ptU4h3Nzusht9k9fPJpK+0O1QuPcCH01nw5LcoqShIXl9XtO9Uf6CJoXDpPdTdnPIf14yBRTzjxV4jX4TlNKNq+X644CcK+BsHqHdFKvhw/L46Q5TbOAB91ZnYeMT99BkN8rWP56EA/thTuH1cg6cY765AizlYMqBFnI72uO8FM7IVCiICiJ50MgFgBlksJYvO8QeHvriK2KWVBiaOEL44bwfOusBcSaHRu/895QT8y2/iLQ4HxXbxL8Q22zOuXmo3vI+S4Ty+AEC+P0ZZIx71hLbrgCemfNRVFZSG+rCgYpuw93P/aWeE+b/HO0=
  on:
    branch: master
