name: main
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .next/cache
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          version: '12.x'
      - run: yarn install --pure-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
