name: Test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install --pure-lockfile 
      - run: yarn test
      - run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}